# Generated by Django 5.2.3 on 2025-06-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color de fondo del botón (puedes usar nombre, hex, rgb, etc). Ej: #ff0000 o red', max_length=20),
            preserve_default=False,
        ),
    ]
