# Generated by Django 5.2.3 on 2025-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text="Nombre del ícono FontAwesome (ej: 'fas fa-gamepad', 'fas fa-tv')", max_length=50),
        ),
    ]
