# Generated by Django 5.2.3 on 2025-06-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(help_text="Color del botón (hex, nombre, etc. Ej: '#ff0000' o 'red')", max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text="Clase de ícono FontAwesome (ej: 'fas fa-gamepad', 'fas fa-tv')", max_length=50),
        ),
    ]
