# Generated by Django 5.2.3 on 2025-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_categoria_color_alter_categoria_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='color',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text="Clase de ícono (ej: 'mdi:gamepad-variant')", max_length=50),
        ),
    ]
