# Generated by Django 5.2.3 on 2025-06-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_slug_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(help_text='Descripción breve para mostrar en la tarjeta del producto', max_length=150),
        ),
        migrations.CreateModel(
            name='DescripcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('variantes', models.TextField(blank=True, help_text='HTML o texto plano para variantes (botones, precios)')),
                ('caracteristicas', models.TextField(blank=True, help_text='HTML con íconos y características destacadas')),
                ('descripcion_larga', models.TextField(blank=True, help_text='Texto completo con beneficios y detalles')),
                ('especificaciones', models.TextField(blank=True, help_text='HTML o JSON con especificaciones técnicas')),
                ('accesorios', models.TextField(blank=True, help_text='Accesorios compatibles u opcionales')),
                ('video_url', models.URLField(blank=True, help_text='URL del video de YouTube o demostración')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='tienda.producto')),
            ],
        ),
    ]
