# Generated by Django 5.2.3 on 2025-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_producto_descripcion_descripcionproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descripcionproducto',
            options={'verbose_name': 'Descripción avanzada', 'verbose_name_plural': 'Descripciones de productos'},
        ),
        migrations.AlterField(
            model_name='descripcionproducto',
            name='accesorios',
            field=models.TextField(blank=True, help_text='Accesorios compatibles u opcionales. Usa doble enter para separar líneas'),
        ),
        migrations.AlterField(
            model_name='descripcionproducto',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Texto completo con beneficios y detalles. Usa doble enter para párrafos.'),
        ),
        migrations.AlterField(
            model_name='descripcionproducto',
            name='variantes',
            field=models.TextField(blank=True, help_text='HTML con botones de variantes. Usa data-sku, data-price, data-old-price si aplica.'),
        ),
    ]
