# Generated by Django 5.2.3 on 2025-06-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_descripcionproducto_variantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianteproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='descripcion',
            field=models.ForeignKey(default=1, help_text='Relación con descripción avanzada del producto', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tienda.descripcionproducto'),
            preserve_default=False,
        ),
    ]
