# Generated by Django 5.2.3 on 2025-06-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_varianteproducto_producto_producto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_variante_estandar',
            field=models.CharField(default='512GB Estándar', help_text='Nombre de la variante estándar. Ej: 512GB estándar, Edición base', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Código único de esta versión estándar', max_length=100),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='nombre',
            field=models.CharField(help_text='Ej: 1TB Edición especial, Azul', max_length=100),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='sku',
            field=models.CharField(help_text='Código único de esta variante (visible o interno)', max_length=100),
        ),
    ]
