# Generated by Django 5.2.3 on 2025-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_producto_nombre_variante_estandar_alter_producto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionproducto',
            name='titulo_personalizado',
            field=models.CharField(blank=True, help_text='Ej: PlayStation 5 Edición Digital', max_length=100),
        ),
    ]
