# Generated by Django 5.2.3 on 2025-06-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_descripcionproducto_titulo_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionproducto',
            name='titulo_superior',
            field=models.CharField(blank=True, help_text='Texto pequeño superior (Ej: Consola de videojuegos)', max_length=100),
        ),
        migrations.AlterField(
            model_name='descripcionproducto',
            name='titulo_personalizado',
            field=models.CharField(blank=True, help_text='Título principal grande (Ej: PlayStation 5 Edición Digital)', max_length=100),
        ),
    ]
