# Generated by Django 5.2.3 on 2025-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_descripcionproducto_titulo_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_variante_estandar',
            field=models.CharField(blank=True, help_text='Nombre de la variante estándar. Ej: 512GB estándar, Edición base', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del producto o versión principal', max_digits=10),
        ),
    ]
