# Generated by Django 5.2.3 on 2025-06-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_producto_nombre_variante_estandar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcionproducto',
            name='especificaciones',
        ),
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Procesador, Memoria, Resolución', max_length=100)),
                ('valor', models.CharField(help_text='Ej: AMD Ryzen 5, 1TB SSD, 4K HDR', max_length=255)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='tienda.descripcionproducto')),
            ],
        ),
    ]
